import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans, Abhaya_Libre, Dancing_Script} from "next/font/google";
import "./globals.css";


const abhaya_libre = Abhaya_Libre({
  subsets: ["latin"],
  weight: ["600"], 
  variable: "--font-abhaya",
})

const dancing_script = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing",
})

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["600"], 
  variable: "--font-nunito",
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${abhaya_libre.variable} ${nunito_sans.variable} ${dancing_script.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
