import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans, Abhaya_Libre, Dancing_Script, Roboto} from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";


const abhaya_libre = Abhaya_Libre({
  subsets: ["latin"],
  weight: ["600"], 
  variable: "--font-abhaya",
})

const dancing_script = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing",
})

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300","600", "700", "800", "900"], 
  variable: "--font-nunito",
})

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        ${abhaya_libre.variable} ${nunito_sans.variable} ${dancing_script.variable} ${roboto.variable} bg-base antialiased`}
      >
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
